-- Migration 002: Add Deal Desk Commercial Terms & Owner Columns
-- Date: 2026-08-27

ALTER TABLE deals ADD COLUMN IF NOT EXISTS discount_pct NUMERIC DEFAULT 0.0;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS contract_months INT DEFAULT 12;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS payment_terms TEXT DEFAULT 'annual_upfront';
ALTER TABLE deals ADD COLUMN IF NOT EXISTS custom_sla BOOLEAN DEFAULT false;
ALTER TABLE deals ADD COLUMN IF NOT EXISTS tier TEXT DEFAULT 'growth';
ALTER TABLE deals ADD COLUMN IF NOT EXISTS owner TEXT DEFAULT 'Rep 1';

ALTER TABLE leads ADD COLUMN IF NOT EXISTS owner TEXT DEFAULT 'Rep 1';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS owner TEXT DEFAULT 'Rep 1';
